export const ActionTypes = {
     

    SET_STATES : 'SET_STATES',
    SET_CITIES : 'SET_CITIES',
    SET_HIGHER_EDUCATION: 'SET_HIGHER_EDUCATION',
    SUBMIT_FORM_SUCCESS: 'SUBMIT_FORM_SUCCESS',
    RESET_FORM : 'RESET_FORM'
   

}