export const ActionTypes = {
     

    SET_STATES : 'SET_STATES',
    SET_CITIES : 'SET_CITIES',
    SET_HIGHER_EDUCATION: 'SET_HIGHER_EDUCATION',
    SUBMIT_FORM_SUCCESS: 'SUBMIT_FORM_SUCCESS',
    RESET_FORM : 'RESET_FORM',
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS', 
    ADMIN_LOGIN_FAILURE: 'ADMIN_LOGIN_FAILURE', FETCH_STUDENTS_SUCCESS : 'FETCH_STUDENTS_SUCCESS',
    FETCH_STUDENTS_ERROR : 'FETCH_STUDENTS_ERROR',   
    SEND_EMAIL_SUCCESS : 'SEND_EMAIL_SUCCESS',
    SEND_EMAIL_FAILURE : 'SEND_EMAIL_FAILURE'
   

   

}