export const ActionTypes = {
     

    SET_STATES : 'SET_STATES',
    SET_CITIES : 'SET_CITIES',
    SET_HIGHER_EDUCATION: 'SET_HIGHER_EDUCATION',
    SUBMIT_FORM_SUCCESS: 'SUBMIT_FORM_SUCCESS',
    RESET_FORM : 'RESET_FORM',
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS', 
    ADMIN_LOGIN_FAILURE: 'ADMIN_LOGIN_FAILURE', FETCH_STUDENTS_SUCCESS : 'FETCH_STUDENTS_SUCCESS',
    FETCH_STUDENTS_ERROR : 'FETCH_STUDENTS_ERROR',   
    SEND_EMAIL_SUCCESS : 'SEND_EMAIL_SUCCESS',
    SEND_EMAIL_FAILURE : 'SEND_EMAIL_FAILURE',
    UPDATE_EMAIL_STATUS : 'UPDATE_EMAIL_STATUS',

    UPLOAD_STATE: 'UPLOAD_STATE',
    EDIT_STATE: 'EDIT_STATE',
    FETCH_STATE_BY_ID: 'FETCH_STATE_BY_ID',
    DEACTIVATE_STATE_SUCCESS: 'DEACTIVATE_STATE_SUCCESS',

    UPLOAD_CITY: 'UPLOAD_CITY',
    EDIT_CITY: 'EDIT_CITY',
    FETCH_CITY: 'FETCH_CITY',
    FETCH_CITY_BY_ID: 'FETCH_CITY_BY_ID',
    DEACTIVATE_CITY_SUCCESS: 'DEACTIVATE_CITY_SUCCESS',

    UPLOAD_EDUCATION: 'UPLOAD_EDUCATION',
    EDIT_EDUCATION: 'EDIT_EDUCATION',
    FETCH_EDUCATION_BY_ID: 'FETCH_EDUCATION_BY_ID',
    DEACTIVATE_EDUCATION_SUCCESS: 'DEACTIVATE_EDUCATION_SUCCESS',   

}